<html>
	<head>
		<title>Menu </title>
			<style>
				body{
					margin: 0;
					background-color: #ccffcc;
				}
			#menu ul{
				margin: 0;
				background-color: #00cc00;
				list-style: none;
			}
			#menu ul li{ 
				display: inline;
				color: white;
			}
			#menu ul li a{
				padding: 10px 15px; 
				display: inline-block; 
				
				color: white; 
				text-decoration: none; 
			}
			#menu ul li a:hover{ 
				color: #336633;
			}
			</style>
	</head>

<body>
	<div id="menu">  <!-- id é o que vai trazer do  css-->
		<ul>
			<li> <center><h1><i><b>INSTRUMENTOS MUSICAIS</b></h1></center></li>
			<hr>
			<li><a href= "inicio.php">Inicio</a></li>
			<li><a href= "cordas.php">Cordas</a></li>
			<li><a href= "sopro.php">Sopro</a></li>
			<li><a href= "percursao.php">Percursão</a></i></li>
		</ul>
	</div>
</body>
</html>